### ISSUE TITLE
Palm trees are busted

### ISSUE THREAD

**Issue by PJB3005** [PJB3005/Drizzle#15]
Reported on discord

**Comment by Myrmice** [comment]
Sending you the particular editor files might be useful :

![SD_D02](https://user-images.githubusercontent.com/6873681/148689991-fb24815e-54ee-4983-b584-d138de1451e8.png)
[SD_D02.txt](https://github.com/PJB3005/Drizzle/files/7835379/SD_D02.txt)

**Comment by PJB3005** [comment]
Can't reproduce from the original image sent on Discord, probably fixed by b6859f584e62e13c2ecfa7a82c1a7f5e3cb3d50c.
